### ISSUE TITLE
Data Science with Python : Regression analysis (Linear regression, Logistics regression)

### ISSUE THREAD

**Issue by ankit-kmar** [girlscript/winter-of-contributing#5848] opened 2021-10-14 13:38 UTC
### Description

Welcome to 'DSWP' Team, good to see you here

In this issue, you will make a tutorial and notebook about the Regression analysis (Linear regression, Logistics regression)

To get assigned to this issue, add your serial numbers mentioned in the spreadsheet of "Data Science with Python", the approach one would follow, and choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

If you had referred any resources, add them up in "DS Resources". Similarly if you had used datasets, include them in "DS Datasets".

Domain: Machine Learning

Mentors Assigned :Ankit Kumar / Ishika Kesarwani

Start from: you can use this notebook to give you a sample overview

Points to Note :

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

"Issue Title" and "PR Title should be the same. Include issue number along with it.

Changes should be made inside the Datascience_With_Python/ directory & Datascience_With_Python branch.

Follow Contributing Guidelines & Code of Conduct before start Contributing.

This issue is only for 'GWOC' contributors of 'DSWP' domain.

All the best. Enjoy your journey ahead. 😎

### Domain

Datascience with Python

### Type of Contribution

Audio, Video, Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Meet-011** [comment] 2021-10-14 19:05
Name: Meet Panchal
Batch:  8
Type : Documentation
Approach: Brief about Linear regression, Logistics regression
@prathimacode-hub /assign Documentation

**Comment by prathimacode-hub** [comment] 2021-10-16 05:53
Issue assigned to @Meet-011 for documentation

**Comment by gohil-jay** [comment] 2021-11-01 06:53
Greetings mam @prathimacode-hub, as this issue hasn't been solved since 16 days, I would like to work on the documentation part on my end.

Details -->
Name: Jay Gohil
Serial No: 124
Batch: 4
Issue Number: 5848
Type: Documentation

Approach: Create a detailed Jupyter Notebook with code as well as explanation of Linear and Logistic regression evaluation (and how to analyze and compare them) that provides all necessary details pertaining to regression analysis in a concise manner.

Please assign this to me!

**Comment by prathimacode-hub** [comment] 2021-11-01 16:53
Since there is no response neither information from your end, this issue isn't assigned to you anymore. Next time, express your interest on issues only when you could work on it. Holding issue for quite a long period isn't right. @Meet-011 

@gohil-jay, issue assigned for documentation

**Comment by ashish-reddy-20-08** [comment] 2021-11-30 09:59
@prathimacode-hub , Mam
I am M. Ashish Reddy. I would like to do video on this issue.
Batch number: 5
serial number:174.
Approach: A detailed explanation with examples and real life uses

**Comment by prathimacode-hub** [comment] 2021-11-30 10:00
Issue assigned to @ashish-reddy-20-08 for video contribution

**Comment by prathimacode-hub** [comment] 2021-11-30 10:08
Issue assigned to @deepthi1107 for audio contribution

**Closed** 2021-12-02 11:17 UTC
Labels: documentation, GWOC21, Video, DSWP, Audio
