### ISSUE TITLE
Data Science with Python: Least angle Regression (LARS)

### ISSUE THREAD

**Issue by Pushpit07** [girlscript/winter-of-contributing#6365] opened 2021-10-19 07:06 UTC
### Description

Welcome to the 'DSWP' Team, good to see you here.

With this issue, readers will get introduced to the core information about 'Least angle Regression (LARS)'.

To get assigned to this issue, add your serial numbers mentioned in the spreadsheet of "Data Science with Python", the approach one would follow and the choice you prefer (Documentation, Audio, Video). You can go with all three or any number of options you're interested to work on.

If you had referred any resources, add them up in "DS Resources". Similarly, if you had used datasets, include them in "DS Datasets".

Domain: Statistics

Mentors Assigned : @Pushpit07 / @aishanii

Points to Note :

The issues will be assigned on a first come first serve basis, 1 Issue == 1 PR.

"Issue Title" and "PR Title" should be the same. Include issue number along with it.

Changes should be made inside the Datascience_With_Python/ directory & Datascience_With_Python branch.

Follow Contributing Guidelines & Code of Conduct before start Contributing.

This issue is only for 'GWOC' contributors of 'DSWP' domain.

All the best. Enjoy your journey ahead. 😎

### Domain

Datascience with Python

### Type of Contribution

Audio, Video, Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by prathimacode-hub** [comment] 2021-10-19 12:20
Issue assigned to @vishnupriya129 for documentation. Your approach is not sufficient. It should be detailed enough.

**Comment by gohil-jay** [comment] 2021-11-01 06:36
Greetings mam @prathimacode-hub, as this issue hasn't been solved since 13 days, I would like to work on the documentation part on my end.

Details -->
Name: Jay Gohil
Serial No: 124
Batch: 4
Issue Number: 6365
Type: Documentation

Approach: Create a detailed Jupyter Notebook with code as well as explanation of Least Angle Regression that provides all necessary details pertaining to LAR in a comprehensive manner.

Please assign this to me!

**Comment by vishnupriya129** [comment] 2021-11-01 11:47
@prathimacode-hub mam I have worked on it but when I make PR then the changes are automatically adding in my old PR what should I do to create pull request for this issue.

**Comment by prathimacode-hub** [comment] 2021-11-01 11:51
Do you have any pending PR's? @vishnupriya129

**Comment by prathimacode-hub** [comment] 2021-11-01 11:52
> Greetings mam @prathimacode-hub, as this issue hasn't been solved since 13 days, I would like to work on the documentation part on my end.
> 
> Details --> Name: Jay Gohil Serial No: 124 Batch: 4 Issue Number: 6365 Type: Documentation
> 
> Approach: Create a detailed Jupyter Notebook with code as well as explanation of Least Angle Regression that provides all necessary details pertaining to LAR in a comprehensive manner.
> 
> Please assign this to me!

Contributor work's is done, she is yet to do PR. @gohil-jay

**Comment by vishnupriya129** [comment] 2021-11-01 11:54
@prathimacode-hub my another PR review is in pending mam

**Comment by prathimacode-hub** [comment] 2021-11-01 12:06
> @prathimacode-hub my another PR review is in pending mam

from which domain? You can take help from mentors who are assigned to you. They will help you out. I could have but I have no data or software in my laptop to showcase you with the process. I lost all to laptop malfunctioning. @vishnupriya129

**Comment by vishnupriya129** [comment] 2021-11-01 12:10
@prathimacode-hub In this domain only mam. issue no: #5977 Evaluating Algorithms. My PR is under your review only mam.

**Comment by prathimacode-hub** [comment] 2021-11-01 12:35
Changes has been requested. Is it done? @vishnupriya129

**Comment by vishnupriya129** [comment] 2021-11-01 12:38
@prathimacode-hub I am working on it. I will complete it soon.

**Comment by vishnupriya129** [comment] 2021-11-13 16:45
@prathimacode-hub Mam can you please review this PR

**Comment by deepthi1107** [comment] 2021-11-28 16:16
Hello, I am Deepthi M with serial number:172, Batch-5. I would like to do audio on this issue.
My approach: a detailed explanation

**Comment by prathimacode-hub** [comment] 2021-11-28 16:27
Issue assigned to @deepthi1107 for audio contribution

**Comment by ashish-reddy-20-08** [comment] 2021-11-29 11:26
@prathimacode-hub , Mam
I am M. Ashish Reddy. I would like to do video on this issue.
Batch number: 5
serial number:174.
Approach: A detailed explanation with examples and real life uses

**Comment by prathimacode-hub** [comment] 2021-11-29 11:28
Issue assigned to @ashish-reddy-20-08 for video contribution

**Closed** 2021-11-29 16:41 UTC
Labels: documentation, GWOC21, Video, DSWP, Audio
