### ISSUE TITLE
Merge Sort using C++ Language

### ISSUE THREAD

**Issue by priyanshu688** [girlscript/winter-of-contributing#6335] opened 2021-10-18 16:48 UTC
### Description

What is Merge Sort? Briefly Explain this and also Its Algorithm. Also Write one program which implement Merge Sort.

### Domain

DSA

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Suvraneel** [comment] 2021-10-19 11:20
duplicate of #4054 by @rajraii

**Closed by Suvraneel** 2021-10-19 11:20 UTC
Labels: documentation, GWOC21, DSA, Assigned
