### ISSUE TITLE
Constructor and Destructor in cpp

### ISSUE THREAD

**Issue by SHUKLA-KUSHAGRA** [girlscript/winter-of-contributing#2371] opened 2021-09-24 04:46 UTC
### Description

In this we will be discussing in brief about constructors and destructors in cpp.

### Domain

C/CPP

### Type of Contribution

Documentation

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CONTRIBUTING.md) & [Code of conduct](https://github.com/girlscript/winter-of-contributing/blob/main/.github/CODE_OF_CONDUCT.md) of this project.

**Comment by Suvraneel** [comment] 2021-09-28 15:13
Duplicate of #858

**Closed** 2021-09-28 15:14 UTC
Labels: documentation, duplicate, GWOC21, Assigned, C/CPP
